/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import {
  Bookmark, Book, Briefcase, Calendar, Camera, Clock, Code, Coffee, Compass, Database, File, FileText, Folder, Globe, Heart, Home, Image, Inbox, Layers, Layout, Link, List, Mail, Map, MessageCircle, Monitor, Music, Package, PenTool, Phone, Rocket, Search, Settings, Share2, ShoppingBag, ShoppingCart, Star, Tag, Target, Terminal, Trash, TrendingUp, Tv, Upload, User, Video, Zap, Archive, Award, Bell, Box, Brush, Bug, Building, BarChart, Activity, CheckCircle, Cpu, Clipboard, Cloud, Crown, Diamond, Download, Edit, Eye, Feather, Film, Filter, Flag, FlaskConical, Gamepad, Gift, GraduationCap, Hammer, Headphones, Key, Laptop, Leaf, Lightbulb, Lock, Magnet, MapPin, Megaphone, Moon, Mountain, Palette, Send, Paperclip, Pen, Plane, Plug, Printer, Puzzle, Radio, RefreshCw, Shield, Signal, Smile, Speaker, Sun, Thermometer, Ticket, Timer, Trees, Trophy, Truck, Umbrella, Wallet, Watch, Wifi, Wind, Wrench, XCircle
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string; size?: number; style?: React.CSSProperties }>> = {
  bookmark: Bookmark,
  book: Book,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  database: Database,
  file: File,
  'file-text': FileText,
  folder: Folder,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  layers: Layers,
  layout: Layout,
  link: Link,
  list: List,
  mail: Mail,
  map: Map,
  'message-circle': MessageCircle,
  monitor: Monitor,
  music: Music,
  package: Package,
  'pen-tool': PenTool,
  phone: Phone,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  star: Star,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  tool: Wrench,
  trash: Trash,
  'trending-up': TrendingUp,
  tv: Tv,
  upload: Upload,
  user: User,
  video: Video,
  zap: Zap,
  archive: Archive,
  award: Award,
  bell: Bell,
  box: Box,
  brush: Brush,
  bug: Bug,
  building: Building,
  'bar-chart': BarChart,
  activity: Activity,
  'check-circle': CheckCircle,
  cpu: Cpu,
  clipboard: Clipboard,
  cloud: Cloud,
  crown: Crown,
  diamond: Diamond,
  download: Download,
  edit: Edit,
  eye: Eye,
  feather: Feather,
  film: Film,
  filter: Filter,
  flag: Flag,
  flask: FlaskConical,
  gamepad: Gamepad,
  gift: Gift,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  headphones: Headphones,
  key: Key,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  magnet: Magnet,
  'map-pin': MapPin,
  megaphone: Megaphone,
  moon: Moon,
  mountain: Mountain,
  palette: Palette,
  send: Send,
  paperclip: Paperclip,
  pen: Pen,
  plane: Plane,
  plug: Plug,
  printer: Printer,
  puzzle: Puzzle,
  radio: Radio,
  'refresh-cw': RefreshCw,
  shield: Shield,
  signal: Signal,
  smile: Smile,
  speaker: Speaker,
  sun: Sun,
  thermometer: Thermometer,
  ticket: Ticket,
  timer: Timer,
  tree: Trees,
  trophy: Trophy,
  truck: Truck,
  umbrella: Umbrella,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  'x-circle': XCircle,
};

export const ALL_ICONS_LIST = Object.keys(ICON_MAP);

interface LucideIconProps {
  name: string;
  className?: string;
  size?: number;
  style?: React.CSSProperties;
}

export const LucideIcon: React.FC<LucideIconProps> = ({ name, className, size = 14, style }) => {
  const IconComponent = ICON_MAP[name] || Folder;
  return <IconComponent className={className} size={size} style={style} />;
};
